services:
  web-service:
    image: node:22-alpine
    command: npm run start
    working_dir: /app
    volumes:
      - ./index.html:/app/index.html
      - ./index.js:/app/index.js
      - ./package.json:/app/package.json

  playwright:
    image: "mcr.microsoft.com/playwright:v1.51.1-noble"
    depends_on:
      - web-service
    command: npx -y playwright@1.51.1 run-server --port 3005 --host 0.0.0.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3005:3005"
